FROM manjarolinux/base:latest AS base

LABEL version="1.2"
LABEL description="Community Build Package/ISO"
LABEL maintainer="Tales A. Mendonça <talesam@gmail.com>"

# Squashing the whole base image into one layer
FROM scratch AS build
COPY --from=base / /

COPY pacman.conf /etc/pacman.conf

ENV LANG=en_US.UTF-8
ENV PATH="/usr/bin:${PATH}"

RUN uname -m \
    && pacman-key --init \
    && echo 'Server = https://mirrors2.manjaro.org/stable/$repo/$arch' > /etc/pacman.d/mirrorlist \
    && pacman-key -r 45EC44879815E2A6 \
    && pacman-key --lsign-key 45EC44879815E2A6

RUN pacman -Syyu --noconfirm --needed archlinux-keyring manjaro-keyring biglinux-keyring

RUN pacman-key --populate archlinux manjaro biglinux

RUN pacman -S --needed --noconfirm \
        base \
        git \
        github-cli \
        nano \
        wget \
        rsync \
        tmate \
        openssh \
        manjaro-chrootbuild

# Tente instalar o community-keyring separadamente
RUN pacman -S --needed --noconfirm community-keyring || echo "Falha ao instalar community-keyring"

RUN pacman -Scc --noconfirm \
    && rm -rf /var/cache/pacman/pkg/* \
    && rm -rf /usr/share/{doc,man} \
    && rm -rf /var/log/* \
    && rm -rf /tmp/* \
    && rm -rf /var/tmp/*

RUN sed -i 's/#en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/g' /etc/locale.gen \
    && locale-gen

RUN echo 'PACKAGER="Community Package/ISO Build <talesam@gmail.com>"' >> /etc/makepkg.conf

# Final docker image 
FROM scratch AS release
COPY --from=build / /
CMD ["/bin/bash"]